"<b style='color:black;'>water</b>" = "water", 
"<b style='color:red;'>glyphosate</b>" =  "glyphosate", 
"<b style='color:blue;'>dicamba</b>" =   "dicamba", 
"<b style='color:blue;'>dicamba</b> + <b style='color:red;'>glyphosate</b>" = "dicamba+glyphosate",
"<b style='color:blue;'>dicamba</b> + <b style='color:red;'>glyphosate</b> + <b style='color:darkgreen;'>DRA 1</b>" = "dicamba+glyphosate+dra1",
"<b style='color:blue;'>dicamba</b> + <b style='color:red;'>glyphosate</b> + <b style='color:lightgreen;'>DRA 2</b>" = "dicamba+glyphosate+dra2", 
"<b style='color:blue;'>dicamba</b> + <b style='color:red;'>glyphosate</b> + <b style='color:orange;'>clethodim</b> + <b style='color:darkgreen;'>DRA 1</b>" = "dicamba+glyphosate+clethodim+dra1",
"<b style='color:blue;'>dicamba</b> + <b style='color:red;'>glyphosate</b> + <b style='color:orange;'>clethodim</b> + <b style='color:lightgreen;'>DRA 2</b>" = "dicamba+glyphosate+clethodim+dra2",
"<b style='color:blue;'>dicamba</b> + <b style='color:red;'>glyphosate</b> + <b style='color:orange;'>clethodim</b> + acetochlor + <b style='color:darkgreen;'>DRA 1</b>" = "dicamba+glyphosate+clethodim+acetochlor+dra1",
"<b style='color:blue;'>dicamba</b> + <b style='color:red;'>glyphosate</b> + <b style='color:orange;'>clethodim</b> + acetochlor + DRA 2<b style='color:lightgreen;'>DRA 2</b>" = "dicamba+glyphosate+clethodim+acetochlor+dra2",
"<b style='color:blue;'>dicamba</b> + <b style='color:red;'>glyphosate</b> + <b style='color:orange;'>clethodim</b> + *S*-metolachlor + <b style='color:darkgreen;'>DRA 1</b>" = "dicamba+glyphosate+clethodim+s-metolachlor+dra1",
"<b style='color:blue;'>dicamba</b> + <b style='color:red;'>glyphosate</b> + <b style='color:orange;'>clethodim</b> + *S*-metolachlor + <b style='color:lightgreen;'>DRA 2</b>" = "dicamba+glyphosate+clethodim+s-metolachlor+dra2", 
"<b style='color:blue;'>dicamba</b> + <b style='color:red;'>glyphosate</b> + glufosinate" = "dicamba+glyphosate+glufosinate",
"<b style='color:blue;'>dicamba</b> + <b style='color:red;'>glyphosate</b> + glufosinate + <b style='color:darkgreen;'>DRA 1</b>" = "dicamba+glyphosate+glufosinate+dra1",
"<b style='color:blue;'>dicamba</b> + <b style='color:red;'>glyphosate</b> + glufosinate + <b style='color:lightgreen;'>DRA 2</b>" = "dicamba+glyphosate+glufosinate+dra2",
"<b style='color:blue;'>dicamba</b> + <b style='color:red;'>glyphosate</b> + glufosinate + <b style='color:orange;'>clethodim</b>+ <b style='color:darkgreen;'>DRA 1</b>" = "dicamba+glyphosate+glufosinate+clethodim+dra1",
"<b style='color:blue;'>dicamba</b> + <b style='color:red;'>glyphosate</b> + glufosinate + <b style='color:orange;'>clethodim</b> + <b style='color:lightgreen;'>DRA 2</b>" = "dicamba+glyphosate+glufosinate+clethodim+dra2"))