---
title: "wind_tunnel2"
author: "Maxwel Coura Oliveira"
date: "2/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(ggtext)
library(tidytext)
library(ggthemes)
library(broom)
library(patchwork)
```


```{r}
data <- read.csv("windtunnel_data.csv") %>% 
  janitor::clean_names() %>% 
  mutate_if(is_character, as_factor) %>% 
  mutate(orifice_size = as_factor(orifice_size))
```


```{r linear-model}
lm_mod <- 
  linear_reg() %>% 
  set_engine("lm")
```

# Drifable fines

```{r}
lm_fit_drift <-
  lm_mod %>% 
  fit(fines_200 ~ nozzle * solution_name * orifice_size * pressure, data = data)
```

# dv50

```{r}
lm_fit_dv <- 
  lm_mod %>% 
  fit(dv50 ~ nozzle * solution_name * orifice_size * pressure, data = data)

```


```{r}
new_points <- expand.grid(pressure = 40,
                          solution_name = unique(data$solution_name),
                        orifice_size = c("0.3", "0.4"),
                        nozzle = unique(data$nozzle)) %>% 
  mutate(sol_number = as.numeric(solution_name)) %>% 
  dplyr::select(sol_number, solution_name, everything()) 
```


```{r}
#Getting predited values
mean_pred_drift <- predict(lm_fit_drift, new_data = new_points)
mean_pred_dv <- predict(lm_fit_dv, new_data = new_points)
```


```{r}
#Getting conf intervals
conf_int_pred_drift <- predict(lm_fit_drift, 
                         new_data = new_points, 
                         type = "conf_int")


conf_int_pred_dv <- predict(lm_fit_dv, 
                         new_data = new_points, 
                         type = "conf_int")
```

```{r}
data1 <- 
  new_points %>% 
  bind_cols(mean_pred_drift) %>% 
  bind_cols(conf_int_pred_drift)

data2 <- 
  new_points %>% 
  bind_cols(mean_pred_dv) %>% 
  bind_cols(conf_int_pred_dv)

category <- data %>% 
  distinct(solution_name, nozzle, orifice_size, pressure, category)

data3 <- data1 %>% 
  dplyr::select(.pred) %>% 
  rename(driftable = .pred) %>% 
  bind_cols(data2) %>% 
  filter(orifice_size == "0.4" & pressure == 40) %>% 
  filter(nozzle %in% c("ULD")) %>% 
  left_join(category)

data4 <- data1 %>% 
  dplyr::select(.pred) %>% 
  rename(driftable = .pred) %>% 
  bind_cols(data2) %>% 
  filter(orifice_size == "0.3" & pressure == 40) %>% 
  filter(nozzle %in% c("AI80", "AI110", "TADFD", "TDXLD", "TTI"))  %>% 
  left_join(category) %>% 
  bind_rows(data3)
```


```{r}
category <- data %>% 
  distinct(solution_name, nozzle, orifice_size, pressure, category) 
```


```{r}
data %>% 
  distinct(nozzle, orifice_size) %>% 
  filter(orifice_size == "0.3")
```



```{r}
data5 <- data4 %>% 
         mutate(solution_name = fct_relevel(solution_name, 
                                  levels = c("water", 
                                             "glyphosate", 
                                             "dicamba", 
                                             "dicamba+glyphosate",
                                             "dicamba+glyphosate+dra1",
                                             "dicamba+glyphosate+dra2", 
                                             "dicamba+glyphosate+clethodim+dra1",
                                             "dicamba+glyphosate+clethodim+dra2",
                           "dicamba+glyphosate+clethodim+acetochlor+dra1",
                           "dicamba+glyphosate+clethodim+acetochlor+dra2",
                           "dicamba+glyphosate+clethodim+s-metolachlor+dra1",
                           "dicamba+glyphosate+clethodim+s-metolachlor+dra2", 
                           "dicamba+glyphosate+glufosinate",
                           "dicamba+glyphosate+glufosinate+dra1",
                           "dicamba+glyphosate+glufosinate+dra2",
                           "dicamba+glyphosate+glufosinate+clethodim+dra1",
                           "dicamba+glyphosate+glufosinate+clethodim+dra2"))) %>% 
  mutate(solution_name = fct_recode(solution_name,
                                  "water" = "water", 
                                  "glyphosate" =  "glyphosate", 
                                  "dicamba" =   "dicamba", 
                                  "dicamba + glyphosate" = "dicamba+glyphosate",
                                  "dicamba + glyphosate + DRA 1" = "dicamba+glyphosate+dra1",
                                  "dicamba + glyphosate + DRA 2" = "dicamba+glyphosate+dra2", 
                                  "dicamba + glyphosate + clethodim + DRA 1" = "dicamba+glyphosate+clethodim+dra1",
                                  "dicamba + glyphosate + clethodim + DRA 2" = "dicamba+glyphosate+clethodim+dra2",
                                  "dicamba + glyphosate + clethodim + acetochlor + DRA 1" = "dicamba+glyphosate+clethodim+acetochlor+dra1",
                                  "dicamba + glyphosate + clethodim + acetochlor + DRA 2" = "dicamba+glyphosate+clethodim+acetochlor+dra2",
                                  "dicamba + glyphosate + clethodim + *S*-metolachlor + DRA 1" = "dicamba+glyphosate+clethodim+s-metolachlor+dra1",
                                  "dicamba + glyphosate + clethodim + *S*-metolachlor + DRA 2" = "dicamba+glyphosate+clethodim+s-metolachlor+dra2", 
                                  "dicamba + glyphosate + glufosinate" = "dicamba+glyphosate+glufosinate",
                                  "dicamba + glyphosate + glufosinate + DRA 1" = "dicamba+glyphosate+glufosinate+dra1",
                                  "dicamba + glyphosate + glufosinate + DRA 2" = "dicamba+glyphosate+glufosinate+dra2",
                                  "dicamba + glyphosate + glufosinate + clethodim+ DRA 1" = "dicamba+glyphosate+glufosinate+clethodim+dra1",
                                  "dicamba + glyphosate + glufosinate + clethodim + DRA 2" = "dicamba+glyphosate+glufosinate+clethodim+dra2"))
```



```{r}
f1 <- data5 %>% 
  filter(orifice_size == "0.3" & pressure == "40") %>% 
  ggplot(aes(x = solution_name, y = .pred, color = category)) +
  geom_point() +
  facet_grid(orifice_size ~ nozzle) +
  geom_point(aes(size = driftable), alpha = 0.4) +
  scale_size_continuous(limits = c(1, 6), breaks=c(1, 2, 3, 4, 5, 6)) +
  scale_x_discrete(limits = rev) +
  geom_errorbar(aes(ymin = .pred_lower, 
                    ymax = .pred_upper),
                width = .2) +
  coord_flip() +
  theme_bw() + 
  labs(y = "", x = "", size = expression(paste("% of predicted difable fines (< 200 ", mu, "m)")), 
    title = "") +
  theme(legend.position = "bottom",
        legend.title = element_text(size = 13, face = "bold"),
        plot.title = element_text(size = 20),
        axis.text.y = element_markdown(size = 12),
        axis.text.x = element_text(size = 11, angle = 45,
                                   hjust = 1,
                                   vjust = 1),
        strip.text = element_markdown(size = 13, face = "bold")) +
  ggsave("figure.pdf", width = 16, height = 8)
```


```{r}
f2 <- data5 %>% 
  filter(orifice_size == "0.4" & pressure == "40") %>% 
  ggplot(aes(x = solution_name, y = .pred, color = category)) +
  geom_point() +
  facet_grid(orifice_size ~ nozzle) +
  geom_point(aes(size = driftable), alpha = 0.4) +
  scale_x_discrete(limits = rev) +
  scale_size_continuous(limits = c(1, 6), breaks=c(1, 2, 3, 4, 5, 6)) +
  geom_errorbar(aes(ymin = .pred_lower, 
                    ymax = .pred_upper),
                width = .2) +
  coord_flip() +
  theme_bw() + 
  labs(y = "", x = "", size = expression(paste("% of predicted difable fines (< 200 ", mu, "m)")), 
    title = "") +
  theme(legend.position = "bottom",
        legend.title = element_text(size = 13, face = "bold"),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size = 11, angle = 45,
                                   hjust = 1,
                                   vjust = 1),
        strip.text = element_markdown(size = 13, face = "bold")) +
  ggsave("figure2.pdf", height = 8, width = 3.2)
```


```{r}
library(ggpubr)
ggarrange(f1, f2, nrow=1, common.legend = TRUE, legend="bottom") +
  ggsave("Figura_3.pdf", width = 15, height = 7, dpi = 600)
```


```{r}
f1 + f2
```

