---
title: "wind_tunnel" 
author: "Maxwel Coura Oliveira"
date: "2/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
library(tidymodels)
library(ggtext)
library(tidytext)
library(ggthemes)
library(broom)
```

```{r}
data %>% 
  distinct(nozzle, orifice_size) %>% 
  filter(orifice_size == "0.3")
```


```{r}
data <- read.csv("windtunnel_data.csv") %>% 
  janitor::clean_names() %>% 
  mutate_if(is_character, as_factor) %>% 
  mutate(orifice_size = as_factor(orifice_size))
```


```{r}
data %>% 
  filter(!nozzle %in%  c("AI110", "TADF")) %>% 
  distinct(nozzle, solution_name)
```


```{r}
data1 <- data %>% 
 filter(!nozzle %in%  c("AI110", "TADF")) %>% 
 group_by(nozzle) %>% 
 nest()
```


```{r linear-model}
lm_mod <- 
  linear_reg() %>% 
  set_engine("lm")
```

# Drifable fines

```{r}
lm_fit_drift <- function(df) {
  lm_mod %>% 
  fit(fines_200 ~ solution_name * orifice_size * pressure, data = df)
}
```

# dv50

```{r}
lm_fit_dv <- function(df) {
  lm_mod %>% 
  fit(dv50 ~ solution_name * orifice_size * pressure, data = df)
}
```


```{r}
data2 <- data1 %>% 
  mutate(drift_mod = map(data, lm_fit_drift),
         tidy_drift = map(drift_mod, tidy),
         glance_drift = map(drift_mod, glance),
         dv_mod = map(data, lm_fit_dv ),
         tidy_dv = map(dv_mod, tidy),
         glance_dv = map(dv_mod, glance))
```


## need to predcit the models
```{r}
new_points <- expand.grid(pressure = 40,
                          solution_name = unique(data$solution_name),
                        orifice_size = "0.3") %>% 
  mutate(sol_number = as.numeric(solution_name)) %>% 
  dplyr::select(sol_number, solution_name, everything()) 
```



```{r ai80}
AI80_mod <- data2$dv_mod[[1]]

AI80_pred <- predict(AI80_mod, new_data = new_points)

AI80_conf_int <- predict(AI80_mod, 
                         new_data = new_points, 
                         type = "conf_int")

AI80_data <- 
  new_points %>% 
  bind_cols(AI80_pred) %>% 
  bind_cols(AI80_conf_int) %>% 
  mutate(nozzle = "AI80")
```


```{r tadfd}
TADFD_mod <- data2$dv_mod[[2]]

TADFD_pred <- predict(TADFD_mod, new_data = new_points)

TADFD_conf_int <- predict(TADFD_mod, 
                         new_data = new_points, 
                         type = "conf_int")

TADFD_data <- 
  new_points %>% 
  bind_cols(TADFD_pred) %>% 
  bind_cols(TADFD_conf_int) %>% 
  mutate(nozzle = "TADFD")
```


```{r tdxld}
TDXLD_mod <- data2$dv_mod[[3]]

TDXLD_pred <- predict(TDXLD_mod, new_data = new_points)

TDXLD_conf_int <- predict(TDXLD_mod, 
                         new_data = new_points, 
                         type = "conf_int")

TDXLD_data <- 
  new_points %>% 
  bind_cols(TDXLD_pred) %>% 
  bind_cols(TDXLD_conf_int) %>% 
  mutate(nozzle = "TDXLD")
```



```{r}
new_points <- expand.grid(pressure = 40,
                          solution_name = unique(data$solution_name),
                        orifice_size = "0.4",
                        nozzle = unique(data$nozzle)) %>% 
  mutate(sol_number = as.numeric(solution_name)) %>% 
  dplyr::select(sol_number, solution_name, everything()) %>% 
  filter(!nozzle %in%  c("AI110", "TADF"))
```


```{r}
#Getting predited values
mean_pred_drift <- predict(lm_fit_drift, new_data = new_points)
mean_pred_dv <- predict(lm_fit_dv, new_data = new_points)
```


```{r}
#Getting conf intervals
conf_int_pred_drift <- predict(lm_fit_drift, 
                         new_data = new_points, 
                         type = "conf_int")


conf_int_pred_dv <- predict(lm_fit_dv, 
                         new_data = new_points, 
                         type = "conf_int")
```


```{r}
category <- data %>% 
  distinct(solution_name, nozzle, pressure, orifice_size) %>% 
  filter(orifice_size == "0.4" & pressure == 40)
```

```{r}
data1 <- 
  new_points %>% 
  bind_cols(mean_pred_drift) %>% 
  bind_cols(conf_int_pred_drift)

data2 <- 
  new_points %>% 
  bind_cols(mean_pred_dv) %>% 
  bind_cols(conf_int_pred_dv)

data3 <- data1 %>% 
  dplyr::select(.pred) %>% 
  rename(driftable = .pred) %>% 
  bind_cols(data2) %>% 
  filter(orifice_size == "0.4" & pressure == 40) %>% 
  left_join(category)
```


```{r}
data4 <- data3 %>% 
         mutate(solution_name = fct_relevel(solution_name, 
                                  levels = c("water", 
                                             "glyphosate", 
                                             "dicamba", 
                                             "dicamba+glyphosate",
                                             "dicamba+glyphosate+dra1",
                                             "dicamba+glyphosate+dra2", 
                                             "dicamba+glyphosate+clethodim+dra1",
                                             "dicamba+glyphosate+clethodim+dra2",
                           "dicamba+glyphosate+clethodim+acetochlor+dra1",
                           "dicamba+glyphosate+clethodim+acetochlor+dra2",
                           "dicamba+glyphosate+clethodim+s-metolachlor+dra1",
                           "dicamba+glyphosate+clethodim+s-metolachlor+dra2", 
                           "dicamba+glyphosate+glufosinate",
                           "dicamba+glyphosate+glufosinate+dra1",
                           "dicamba+glyphosate+glufosinate+dra2",
                           "dicamba+glyphosate+glufosinate+clethodim+dra1",
                           "dicamba+glyphosate+glufosinate+clethodim+dra2"))) %>% 
  mutate(solution_name = fct_recode(solution_name,
                                  "water" = "water", 
                                  "glyphosate" =  "glyphosate", 
                                  "dicamba" =   "dicamba", 
                                  "dicamba + glyphosate" = "dicamba+glyphosate",
                                  "dicamba + glyphosate + DRA 1" = "dicamba+glyphosate+dra1",
                                  "dicamba + glyphosate + DRA 2" = "dicamba+glyphosate+dra2", 
                                  "dicamba + glyphosate + clethodim + DRA 1" = "dicamba+glyphosate+clethodim+dra1",
                                  "dicamba + glyphosate + clethodim + DRA 2" = "dicamba+glyphosate+clethodim+dra2",
                                  "dicamba + glyphosate + clethodim + acetochlor + DRA 1" = "dicamba+glyphosate+clethodim+acetochlor+dra1",
                                  "dicamba + glyphosate + clethodim + acetochlor + DRA 2" = "dicamba+glyphosate+clethodim+acetochlor+dra2",
                                  "dicamba + glyphosate + clethodim + *S*-metolachlor + DRA 1" = "dicamba+glyphosate+clethodim+s-metolachlor+dra1",
                                  "dicamba + glyphosate + clethodim + *S*-metolachlor + DRA 2" = "dicamba+glyphosate+clethodim+s-metolachlor+dra2", 
                                  "dicamba + glyphosate + glufosinate" = "dicamba+glyphosate+glufosinate",
                                  "dicamba + glyphosate + glufosinate + DRA 1" = "dicamba+glyphosate+glufosinate+dra1",
                                  "dicamba + glyphosate + glufosinate + DRA 2" = "dicamba+glyphosate+glufosinate+dra2",
                                  "dicamba + glyphosate + glufosinate + clethodim+ DRA 1" = "dicamba+glyphosate+glufosinate+clethodim+dra1",
                                  "dicamba + glyphosate + glufosinate + clethodim + DRA 2" = "dicamba+glyphosate+glufosinate+clethodim+dra2"))
```



```{r}
data4 %>% 
  filter(orifice_size == "0.4" & pressure == "40") %>% 
  ggplot(aes(x = solution_name, y = .pred, color = category)) +
  geom_point() +
  geom_point(aes(size = driftable), alpha = 0.4) +
#  geom_point(data = data, mapping = aes(x = solution_name, y = .pred,  color = category)) +
  scale_x_discrete(limits = rev) +
  geom_errorbar(aes(ymin = .pred_lower, 
                    ymax = .pred_upper),
                width = .2) +
#  scale_color_manual(values = c("black", "red")) +
  facet_grid(~ nozzle) + 
  coord_flip() +
  theme_bw() + 
  labs(y = "", x = "", size = expression(paste("% of predicted difable fines (> 200 ", mu, "m)")), 
    title = "DV50 of herbicide solutions at 40 psi and orifice size = 0.4") +
  theme(legend.position = "bottom",
        legend.title = element_text(size = 13, face = "bold"),
        plot.title = element_text(size = 20),
        axis.text.y = element_markdown(size = 12),
        axis.text.x = element_text(size = 11, angle = 45,
                                   hjust = 1,
                                   vjust = 1),
        strip.text = element_markdown(size = 13, face = "bold")) +
  ggsave("figure.pdf", width = 16, height = 8)
```

