---
title: "RF1_Patternator"
author: "Jesaelen"
date: "3/25/2021" 
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(parsnip)
library(tidymodels)
library(vctrs)
library(hardhat)
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(tidyr)
library(doParallel)
library(ranger)
library(vip)
library(RCurl)
library(purrr)
```

```{r}
data <- read_csv("rf_parameters.csv") %>% 
  mutate_if(is_character, as_factor) 
data
```

```{r}
set.seed(123)
s1_split <- initial_split(data, strata = cv)
s1_train <- training(s1_split)
s1_test <- testing(s1_split)
```

```{r}
set.seed(123)
#Build recipe
s1_rec <- recipe(cv ~ ., data=s1_train)

#Build model
tune_spec <- rand_forest(mtry=tune(), trees=1000, min_n=tune()) %>% 
  set_mode("regression") %>%
  set_engine("ranger") 

#Build your worflow
tune_wf <- workflow() %>%
  add_recipe(s1_rec) %>% 
  add_model(tune_spec) 
```


```{r}
set.seed(123)
s1_folds <- vfold_cv(s1_train)

doParallel::registerDoParallel() 

tune_res <- tune_grid(tune_wf, resamples=s1_folds, grid=20) 
```


```{r}
set.seed(123)
tune_res %>%
  select_best("rmse") 
```

```{r}
set.seed(123)
tune_res %>%
  collect_metrics() %>% 
  filter(.metric =="rmse") %>% 
  pivot_longer(min_n:mtry, values_to="value", names_to="parameter") %>% 
  ggplot(aes(value, mean, color=parameter)) +
  geom_point(show.legend=FALSE) +
  facet_wrap(~ parameter)
```


```{r}
set.seed(123)
rf_grid <- grid_regular(mtry(range=c(1,7)), min_n(range=c(10,40)), levels=5)  

set.seed(123)
regular_res <- tune_grid(tune_wf, resamples=s1_folds, grid=rf_grid) 

regular_res %>%
  select_best("rmse") 
```


```{r}
regular_res %>%
  collect_metrics() %>%
  filter(.metric =="rmse") %>% 
  mutate(min_n = factor(min_n)) %>% 
  ggplot(aes(mtry, mean, color = min_n)) +
  geom_line(alpha=0.5, size=1.5) +
  geom_point()
```



```{r}
set.seed(123)

best_rmse <- select_best(regular_res, "rmse")
final_rf <- finalize_model(tune_spec, best_rmse)

final_rf %>%
  set_engine("ranger", importance="impurity") %>% 
  fit(cv ~ ., data=s1_train) %>%
  #vi() %>% 
  #Dot plot
  vip(geom="point", horizontal=TRUE, aesthetics=list(color="black", size=3)) + 
  theme_light() + 
  theme(plot.title = element_text(hjust=0.5, size=35, face="bold"),
                     axis.title.x = element_text(size=20, color="black"), 
                     legend.title = element_blank(),
                     axis.text.x = element_text(size=15, color="black"),
                     axis.text.y = element_text(size=15, hjust=0, color="black"),
                     strip.text.x = element_text(size=25, color="black", face="bold"),
                     strip.text = element_text(size=13), 
                     panel.background =element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  labs(y="Variable Importance") 
```

```{r}
final_rf %>%
  set_engine("ranger", importance="impurity") %>%
  fit(cv ~ ., data=s1_train) %>% 
  #Bar plot
  vip(geom="col", horizontal=TRUE, aesthetics=list(fill=c("#173F5F", "#20639B", "#3CAEA3", "#F6D55C", "#ED553B"), 
                                                   width= 0.65)) +
  theme_light() + 
  theme(plot.title = element_text(hjust=0.5, size=35, face="bold"),
                     axis.title.x = element_text(size=20, color="black"), 
                     legend.title = element_blank(),
                     axis.text.x = element_text(size=15, color="black"),
                     axis.text.y = element_text(size=15, hjust=0, color="black"),
                     strip.text.x = element_text(size=25, color="black", face="bold"),
                     strip.text = element_text(size=13), 
                     panel.background =element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  labs(y="Variable Importance")
```

```{r}
final_wf <- workflow() %>%
  add_recipe(s1_rec) %>% 
  add_model(final_rf) 

final_res <- final_wf %>%
  last_fit(s1_split)
```

```{r}
final_res %>%
  collect_metrics()
```

```{r}
final_res %>%
  collect_predictions() %>% 
  bind_cols(s1_test)
```

```{r}
ggsave("rf1_patternator.jpeg", dpi = 900, device = "jpeg")
```



#### Analysis for spray solution: Water

```{r}
data <- read_csv("rf_parameters_water.csv") %>% 
  mutate_if(is_character, as_factor) 
data
```

```{r}
set.seed(123)
s1_split <- initial_split(data, strata = cv)
s1_train <- training(s1_split)
s1_test <- testing(s1_split)
```

```{r}
set.seed(123)
#Build recipe
s1_rec <- recipe(cv ~ ., data=s1_train)

#Build model
tune_spec <- rand_forest(mtry=tune(), trees=1000, min_n=tune()) %>% 
  set_mode("regression") %>%
  set_engine("ranger") 

#Build your worflow
tune_wf <- workflow() %>%
  add_recipe(s1_rec) %>% 
  add_model(tune_spec) 
```

```{r}
set.seed(123)
s1_folds <- vfold_cv(s1_train)

doParallel::registerDoParallel() 

tune_res <- tune_grid(tune_wf, resamples=s1_folds, grid=20) 
```

```{r}
set.seed(123)
tune_res %>%
  select_best("rmse") 
```

```{r}
set.seed(123)
tune_res %>%
  collect_metrics() %>% 
  filter(.metric =="rmse") %>% 
  pivot_longer(min_n:mtry, values_to="value", names_to="parameter") %>% 
  ggplot(aes(value, mean, color=parameter)) +
  geom_point(show.legend=FALSE) +
  facet_wrap(~ parameter)
```

```{r}
set.seed(123)
rf_grid <- grid_regular(mtry(range=c(1,6)), min_n(range=c(10,50)), levels=5)  

set.seed(123)
regular_res <- tune_grid(tune_wf, resamples=s1_folds, grid=rf_grid) 

regular_res %>%
  select_best("rmse") 
```

```{r}
regular_res %>%
  collect_metrics() %>%
  filter(.metric =="rmse") %>% 
  mutate(min_n = factor(min_n)) %>% 
  ggplot(aes(mtry, mean, color = min_n)) +
  geom_line(alpha=0.5, size=1.5) +
  geom_point()
```

```{r}
set.seed(123)

best_rmse <- select_best(regular_res, "rmse")
final_rf <- finalize_model(tune_spec, best_rmse)

final_rf %>%
  set_engine("ranger", importance="impurity") %>% 
  fit(cv ~ ., data=s1_train) %>%
  #vi() %>% 
  #Dot plot
  vip(geom="point", horizontal=TRUE, aesthetics=list(color="black", size=3)) + 
  theme_light() + 
  theme(plot.title = element_text(hjust=0.5, size=35, face="bold"),
                     axis.title.x = element_text(size=20, color="black"), 
                     legend.title = element_blank(),
                     axis.text.x = element_text(size=15, color="black"),
                     axis.text.y = element_text(size=15, hjust=0, color="black"),
                     strip.text.x = element_text(size=25, color="black", face="bold"),
                     strip.text = element_text(size=13), 
                     panel.background =element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  labs(y="Variable Importance") 
```

```{r}
final_rf %>%
  set_engine("ranger", importance="impurity") %>%
  fit(cv ~ ., data=s1_train) %>% 
  #Bar plot
  vip(geom="col", horizontal=TRUE, aesthetics=list(fill=c("#20639B", "#F6D55C","#3CAEA3", "#ED553B"), 
                                                   width= 0.65)) +
  theme_light() + 
  theme(plot.title = element_text(hjust=0.5, size=35, face="bold"),
                     axis.title.x = element_text(size=20, color="black"), 
                     legend.title = element_blank(),
                     axis.text.x = element_text(size=15, color="black"),
                     axis.text.y = element_text(size=15, hjust=0, color="black"),
                     strip.text.x = element_text(size=25, color="black", face="bold"),
                     strip.text = element_text(size=13), 
                     panel.background =element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  labs(y="Variable Importance")
```

```{r}
final_wf <- workflow() %>%
  add_recipe(s1_rec) %>% 
  add_model(final_rf) 

final_res <- final_wf %>%
  last_fit(s1_split)
```

```{r}
final_res %>%
  collect_metrics()
```

```{r}
final_res %>%
  collect_predictions() %>% 
  bind_cols(s1_test)
```


```{r}
ggsave("rf1_water.jpeg", dpi = 900, device = "jpeg")
```


#### Analysis for spray solution: Dicamba

```{r}
data <- read_csv("rf_parameters_dicamba.csv") %>% 
  mutate_if(is_character, as_factor) 
data
```

```{r}
set.seed(123)
s1_split <- initial_split(data, strata = cv)
s1_train <- training(s1_split)
s1_test <- testing(s1_split)
```

```{r}
set.seed(123)
#Build recipe
s1_rec <- recipe(cv ~ ., data=s1_train)

#Build model
tune_spec <- rand_forest(mtry=tune(), trees=1000, min_n=tune()) %>% 
  set_mode("regression") %>%
  set_engine("ranger") 

#Build your worflow
tune_wf <- workflow() %>%
  add_recipe(s1_rec) %>% 
  add_model(tune_spec) 
```

```{r}
set.seed(123)
s1_folds <- vfold_cv(s1_train)

doParallel::registerDoParallel() 

tune_res <- tune_grid(tune_wf, resamples=s1_folds, grid=20) 
```

```{r}
set.seed(123)
tune_res %>%
  select_best("rmse") 
```

```{r}
set.seed(123)
tune_res %>%
  collect_metrics() %>% 
  filter(.metric =="rmse") %>% 
  pivot_longer(min_n:mtry, values_to="value", names_to="parameter") %>% 
  ggplot(aes(value, mean, color=parameter)) +
  geom_point(show.legend=FALSE) +
  facet_wrap(~ parameter)
```

```{r}
set.seed(123)
rf_grid <- grid_regular(mtry(range=c(1,4)), min_n(range=c(20,30)), levels=5)  

set.seed(123)
regular_res <- tune_grid(tune_wf, resamples=s1_folds, grid=rf_grid) 

regular_res %>%
  select_best("rmse") 
```

```{r}
regular_res %>%
  collect_metrics() %>%
  filter(.metric =="rmse") %>% 
  mutate(min_n = factor(min_n)) %>% 
  ggplot(aes(mtry, mean, color = min_n)) +
  geom_line(alpha=0.5, size=1.5) +
  geom_point()
```

```{r}
set.seed(123)

best_rmse <- select_best(regular_res, "rmse")
final_rf <- finalize_model(tune_spec, best_rmse)

final_rf %>%
  set_engine("ranger", importance="impurity") %>% 
  fit(cv ~ ., data=s1_train) %>%
  #vi() %>% 
  #Dot plot
  vip(geom="point", horizontal=TRUE, aesthetics=list(color="black", size=3)) + 
  theme_light() + 
  theme(plot.title = element_text(hjust=0.5, size=35, face="bold"),
                     axis.title.x = element_text(size=20, color="black"), 
                     legend.title = element_blank(),
                     axis.text.x = element_text(size=15, color="black"),
                     axis.text.y = element_text(size=15, hjust=0, color="black"),
                     strip.text.x = element_text(size=25, color="black", face="bold"),
                     strip.text = element_text(size=13), 
                     panel.background =element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  labs(y="Variable Importance") 
```

```{r}
final_rf %>%
  set_engine("ranger", importance="impurity") %>%
  fit(cv ~ ., data=s1_train) %>% 
  #Bar plot
  vip(geom="col", horizontal=TRUE, aesthetics=list(fill=c("#20639B", "#3CAEA3","#F6D55C","#ED553B"), 
                                                   width= 0.65)) +
  theme_light() + 
  theme(plot.title = element_text(hjust=0.5, size=35, face="bold"),
                     axis.title.x = element_text(size=20, color="black"), 
                     legend.title = element_blank(),
                     axis.text.x = element_text(size=15, color="black"),
                     axis.text.y = element_text(size=15, hjust=0, color="black"),
                     strip.text.x = element_text(size=25, color="black", face="bold"),
                     strip.text = element_text(size=13), 
                     panel.background =element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  labs(y="Variable Importance")
```

```{r}
final_wf <- workflow() %>%
  add_recipe(s1_rec) %>% 
  add_model(final_rf) 

final_res <- final_wf %>%
  last_fit(s1_split)
```

```{r}
final_res %>%
  collect_metrics()
```

```{r}
final_res %>%
  collect_predictions() %>% 
  bind_cols(s1_test)
```

```{r}
ggsave("rf1_dicamba.jpeg", dpi = 900, device = "jpeg")
```

#### Analysis for spray solution: Dicamba + Intact

```{r}
data <- read_csv("rf_parameters_intact.csv") %>% 
  mutate_if(is_character, as_factor) 
data
```

```{r}
set.seed(123)
s1_split <- initial_split(data, strata = cv)
s1_train <- training(s1_split)
s1_test <- testing(s1_split)
```

```{r}
set.seed(123)
#Build recipe
s1_rec <- recipe(cv ~ ., data=s1_train)

#Build model
tune_spec <- rand_forest(mtry=tune(), trees=1000, min_n=tune()) %>% 
  set_mode("regression") %>%
  set_engine("ranger") 

#Build your worflow
tune_wf <- workflow() %>%
  add_recipe(s1_rec) %>% 
  add_model(tune_spec) 
```

```{r}
set.seed(123)
s1_folds <- vfold_cv(s1_train)

doParallel::registerDoParallel() 

tune_res <- tune_grid(tune_wf, resamples=s1_folds, grid=22) 
```

```{r}
set.seed(123)
tune_res %>%
  select_best("rmse") 
```

```{r}
set.seed(123)
tune_res %>%
  collect_metrics() %>% 
  filter(.metric =="rmse") %>% 
  pivot_longer(min_n:mtry, values_to="value", names_to="parameter") %>% 
  ggplot(aes(value, mean, color=parameter)) +
  geom_point(show.legend=FALSE) +
  facet_wrap(~ parameter)
```

```{r}
set.seed(123)
rf_grid <- grid_regular(mtry(range=c(1,5)), min_n(range=c(0,60)), levels=6)  

set.seed(123)
regular_res <- tune_grid(tune_wf, resamples=s1_folds, grid=rf_grid) 

regular_res %>%
  select_best("rmse") 
```

```{r}
regular_res %>%
  collect_metrics() %>%
  filter(.metric =="rmse") %>% 
  mutate(min_n = factor(min_n)) %>% 
  ggplot(aes(mtry, mean, color = min_n)) +
  geom_line(alpha=0.5, size=1.5) +
  geom_point()
```

```{r}
set.seed(123)

best_rmse <- select_best(regular_res, "rmse")
final_rf <- finalize_model(tune_spec, best_rmse)

final_rf %>%
  set_engine("ranger", importance="impurity") %>% 
  fit(cv ~ ., data=s1_train) %>%
  #vi() %>% 
  #Dot plot
  vip(geom="point", horizontal=TRUE, aesthetics=list(color="black", size=3)) + 
  theme_light() + 
  theme(plot.title = element_text(hjust=0.5, size=35, face="bold"),
                     axis.title.x = element_text(size=20, color="black"), 
                     legend.title = element_blank(),
                     axis.text.x = element_text(size=15, color="black"),
                     axis.text.y = element_text(size=15, hjust=0, color="black"),
                     strip.text.x = element_text(size=25, color="black", face="bold"),
                     strip.text = element_text(size=13), 
                     panel.background =element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  labs(y="Variable Importance") 
```

```{r}
final_rf %>%
  set_engine("ranger", importance="impurity") %>%
  fit(cv ~ ., data=s1_train) %>% 
  #Bar plot
  vip(geom="col", horizontal=TRUE, aesthetics=list(fill=c("#3CAEA3", "#F6D55C", "#20639B","#ED553B"), 
                                                   width= 0.65)) +
  theme_light() + 
  theme(plot.title = element_text(hjust=0.5, size=35, face="bold"),
                     axis.title.x = element_text(size=20, color="black"), 
                     legend.title = element_blank(),
                     axis.text.x = element_text(size=15, color="black"),
                     axis.text.y = element_text(size=15, hjust=0, color="black"),
                     strip.text.x = element_text(size=25, color="black", face="bold"),
                     strip.text = element_text(size=13), 
                     panel.background =element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  labs(y="Variable Importance")
```

```{r}
final_wf <- workflow() %>%
  add_recipe(s1_rec) %>% 
  add_model(final_rf) 

final_res <- final_wf %>%
  last_fit(s1_split)
```

```{r}
final_res %>%
  collect_metrics()
```

```{r}
final_res %>%
  collect_predictions() %>% 
  bind_cols(s1_test)
```

```{r}
ggsave("rf1_intact.jpeg", dpi = 900, device = "jpeg")
```

#### Analysis for spray solution: Dicamba + TPII

```{r}
data <- read_csv("rf_parameters_tpii.csv") %>% 
  mutate_if(is_character, as_factor) 
data
```

```{r}
set.seed(123)
s1_split <- initial_split(data, strata = cv)
s1_train <- training(s1_split)
s1_test <- testing(s1_split)
```

```{r}
set.seed(123)
#Build recipe
s1_rec <- recipe(cv ~ ., data=s1_train)

#Build model
tune_spec <- rand_forest(mtry=tune(), trees=1000, min_n=tune()) %>% 
  set_mode("regression") %>%
  set_engine("ranger") 

#Build your worflow
tune_wf <- workflow() %>%
  add_recipe(s1_rec) %>% 
  add_model(tune_spec) 
```

```{r}
set.seed(123)
s1_folds <- vfold_cv(s1_train)

doParallel::registerDoParallel() 

tune_res <- tune_grid(tune_wf, resamples=s1_folds, grid=20) 
```

```{r}
set.seed(123)
tune_res %>%
  select_best("rmse") 
```

```{r}
set.seed(123)
tune_res %>%
  collect_metrics() %>% 
  filter(.metric =="rmse") %>% 
  pivot_longer(min_n:mtry, values_to="value", names_to="parameter") %>% 
  ggplot(aes(value, mean, color=parameter)) +
  geom_point(show.legend=FALSE) +
  facet_wrap(~ parameter)
```

```{r}
set.seed(123)
rf_grid <- grid_regular(mtry(range=c(1,4)), min_n(range=c(20,30)), levels=5)  

set.seed(123)
regular_res <- tune_grid(tune_wf, resamples=s1_folds, grid=rf_grid) 

regular_res %>%
  select_best("rmse") 
```

```{r}
regular_res %>%
  collect_metrics() %>%
  filter(.metric =="rmse") %>% 
  mutate(min_n = factor(min_n)) %>% 
  ggplot(aes(mtry, mean, color = min_n)) +
  geom_line(alpha=0.5, size=1.5) +
  geom_point()
```

```{r}
set.seed(123)

best_rmse <- select_best(regular_res, "rmse")
final_rf <- finalize_model(tune_spec, best_rmse)

final_rf %>%
  set_engine("ranger", importance="impurity") %>% 
  fit(cv ~ ., data=s1_train) %>%
  #vi() %>% 
  #Dot plot
  vip(geom="point", horizontal=TRUE, aesthetics=list(color="black", size=3)) + 
  theme_light() + 
  theme(plot.title = element_text(hjust=0.5, size=35, face="bold"),
                     axis.title.x = element_text(size=20, color="black"), 
                     legend.title = element_blank(),
                     axis.text.x = element_text(size=15, color="black"),
                     axis.text.y = element_text(size=15, hjust=0, color="black"),
                     strip.text.x = element_text(size=25, color="black", face="bold"),
                     strip.text = element_text(size=13), 
                     panel.background =element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  labs(y="Variable Importance") 
```

```{r}
final_rf %>%
  set_engine("ranger", importance="impurity") %>%
  fit(cv ~ ., data=s1_train) %>% 
  #Bar plot
  vip(geom="col", horizontal=TRUE, aesthetics=list(fill=c("#20639B", "#3CAEA3", "#F6D55C","#ED553B"), 
                                                   width= 0.65)) +
  theme_light() + 
  theme(plot.title = element_text(hjust=0.5, size=35, face="bold"),
                     axis.title.x = element_text(size=20, color="black"), 
                     legend.title = element_blank(),
                     axis.text.x = element_text(size=15, color="black"),
                     axis.text.y = element_text(size=15, hjust=0, color="black"),
                     strip.text.x = element_text(size=25, color="black", face="bold"),
                     strip.text = element_text(size=13), 
                     panel.background =element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  labs(y="Variable Importance")
```

```{r}
final_wf <- workflow() %>%
  add_recipe(s1_rec) %>% 
  add_model(final_rf) 

final_res <- final_wf %>%
  last_fit(s1_split)
```

```{r}
final_res %>%
  collect_metrics()
```

```{r}
final_res %>%
  collect_predictions() %>% 
  bind_cols(s1_test)
```

```{r}
ggsave("rf1_tpii.jpeg", dpi = 900, device = "jpeg")
```

